### ISSUE TITLE
Level 300: Optimization Data Collection - OrgDataModule fails Parameters: [Tags] do not exist in the template

### ISSUE THREAD

**Issue by venom02** [awslabs/aws-well-architected-labs#624]
Hi, I tried following [this guide](https://www.youtube.com/watch?v=IaqtlkkdTs8) from @awssteph but the cloudformation update fails when switching OrgDataModule to yes with

`Parameters: [Tags] do not exist in the template `

in the template, the OrgDataModule is defined as this
```yaml
  OrgDataModule:
    Type: AWS::CloudFormation::Stack
    Condition: DeployOrgDataModule
    Properties:
      TemplateURL:  "https://aws-well-architected-labs.s3.us-west-2.amazonaws.com/Cost/Labs/300_Optimization_Data_Collection/organization_data_dev.yaml"
      Parameters:
        DestinationBucket: !Ref S3Bucket
        GlueRoleARN: !GetAtt GlueRole.Arn
        ManagementAccountRole: !Sub "arn:aws:iam::${ManagementAccountID}:role/${RolePrefix}${ManagementAccountRole}"
        Tags: "Env"
        RolePrefix: !Ref RolePrefix
```

but in the https://aws-well-architected-labs.s3.us-west-2.amazonaws.com/Cost/Labs/300_Optimization_Data_Collection/organization_data_dev.yaml there is no trace of Tags parameter.

can you please check this? thank you
