### ISSUE TITLE
Security Level 300: Multilayered API Security with Cognito and WAF - Missing code for Secrets Manager Rotation Lambda

### ISSUE THREAD

**Issue by georgehb** [awslabs/aws-well-architected-labs#690]
In the provided Cloudformation Template `section3-enhance_security.yaml`, there is a lambda function defined for rotating secrets within the aws secret manager, however the code for the lambda appears to be missing from lambda deployment zip.

The template (below) claims the code should be found within `python-requests-lambda-layer.zip` in a file called `lambda_function` but that file doesn't seem to exist

This is the relevant section of the template
```yaml
  OriginSecretRotateFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Serets Manager Rotation Lambda
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Layers:
        - !Ref PythonRequestsLayer
      #VpcConfig: # For accessing RDS instance
      #  SecurityGroupIds:
      #    - !Ref LambdaSecurityGroup
      #  SubnetIds:
      #    - !Ref WAprivateLambdaSubnet1
      Environment:
        Variables:
          WAFACLID: !GetAtt wafACLR.Id
          WAFACLNAME: !Select [0, !Split ['|', !Ref 'wafACLR']]
          WAFRULEPRI: !Ref WAFRulePriority
          CFDISTROID: !Ref CloudFrontDistribution
          HEADERNAME: !Ref HeaderName
          ORIGINURL: !Ref ApiGatewayURL
          STACKNAME: !Ref AWS::StackName
          AWSREGION: !Ref AWS::Region
      Role: !GetAtt OriginSecretRotateExecutionRole.Arn
      Timeout: 60
      Code:
        S3Bucket: !Ref SBucketName
        S3Key: python-requests-lambda-layer.zip
```

This is the list of files that I see within `python-requests-lambda-layer.zip`. lambda_function is not there
```
python/
├── bin/
├── certifi/
├── certifi-2020.6.20.dist-info/
├── chardet/
├── chardet-3.0.4.dist-info/
├── idna/
├── idna-2.10.dist-info/
├── python-requests.zip
├── requests/
├── requests-2.24.0.dist-info/
├── urllib3/
└── urllib3-1.25.10.dist-info/
```
